apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.11.1
  count: 1
  elasticsearchRef:
    name: "elasticsearch"
  # config:
  #   elasticsearch.hosts:
  #     - https://elasticsearch.example.com:9200
  #   elasticsearch.username: elastic
  #   secureSettings:
  #     - secretName: kibana-elasticsearch-credentials
  #   elasticsearch.ssl.certificateAuthorities: /etc/certs/ca.crt
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      certificate:
        secretName: kibana-tls
        
  # podTemplate:
  #   spec:
  #     containers:
  #     - name: kibana
  #       env:
  #         - name: NODE_OPTIONS
  #           value: "--max-old-space-size=2048"
  #       resources:
  #         requests:
  #           memory: 1Gi
  #           cpu: 0.5
  #         limits:
  #           memory: 2.5Gi
  #           cpu: 2
  #     nodeSelector:
  #       type: frontend